
resources:
- name: slack-schedule
  type: time
  source:
    days: [ Thursday ]
    location: Europe/Dublin
    start: 11:27 AM
    stop: 11:50 AM
    interval: 1h

jobs:
- name: solving-all-the-worlds-problems
  plan:
  - get: slack-schedule
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudopseuci/eu-ci
          tag: latest
      run:
        path: /bin/bash
        args:
          - -c
          - |
            exit 1 
